In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
try:
    df = pd.read_csv("/home/vipul/Machine Learning/Linear Regression/Sleep&Health/Sleep_health_and_lifestyle_dataset.csv")
except:
    print("File not found")

In [3]:
df.head()

Person ID Gender  Age            Occupation  Sleep Duration  \
0          1   Male   27     Software Engineer             6.1   
1          2   Male   28                Doctor             6.2   
2          3   Male   28                Doctor             6.2   
3          4   Male   28  Sales Representative             5.9   
4          5   Male   28  Sales Representative             5.9   

   Quality of Sleep  Physical Activity Level  Stress Level BMI Category  \
0                 6                       42             6   Overweight   
1                 6                       60             8       Normal   
2                 6                       60             8       Normal   
3                 4                       30             8        Obese   
4                 4                       30             8        Obese   

  Blood Pressure  Heart Rate  Daily Steps Sleep Disorder  
0         126/83          77         4200            NaN  
1         125/80          75        10000            NaN  
2         125/80          75        10000            NaN  
3         140/90          85         3000    Sleep Apnea  
4         140/90          85         3000    Sleep Apnea

In [4]:
df['Sleep Disorder'] = df['Sleep Disorder'].fillna('Unknown')
mapping = {'Unknown': 0, 'Sleep Apnea': 1, 'Insomnia': 2}
df['Sleep'] = df['Sleep Disorder'].map(mapping)
df

Person ID  Gender  Age            Occupation  Sleep Duration  \
0            1    Male   27     Software Engineer             6.1   
1            2    Male   28                Doctor             6.2   
2            3    Male   28                Doctor             6.2   
3            4    Male   28  Sales Representative             5.9   
4            5    Male   28  Sales Representative             5.9   
..         ...     ...  ...                   ...             ...   
369        370  Female   59                 Nurse             8.1   
370        371  Female   59                 Nurse             8.0   
371        372  Female   59                 Nurse             8.1   
372        373  Female   59                 Nurse             8.1   
373        374  Female   59                 Nurse             8.1   

     Quality of Sleep  Physical Activity Level  Stress Level BMI Category  \
0                   6                       42             6   Overweight   
1                   6                       60             8       Normal   
2                   6                       60             8       Normal   
3                   4                       30             8        Obese   
4                   4                       30             8        Obese   
..                ...                      ...           ...          ...   
369                 9                       75             3   Overweight   
370                 9                       75             3   Overweight   
371                 9                       75             3   Overweight   
372                 9                       75             3   Overweight   
373                 9                       75             3   Overweight   

    Blood Pressure  Heart Rate  Daily Steps Sleep Disorder  Sleep  
0           126/83          77         4200        Unknown      0  
1           125/80          75        10000        Unknown      0  
2           125/80          75        10000        Unknown      0  
3           140/90          85         3000    Sleep Apnea      1  
4           140/90          85         3000    Sleep Apnea      1  
..             ...         ...          ...            ...    ...  
369         140/95          68         7000    Sleep Apnea      1  
370         140/95          68         7000    Sleep Apnea      1  
371         140/95          68         7000    Sleep Apnea      1  
372         140/95          68         7000    Sleep Apnea      1  
373         140/95          68         7000    Sleep Apnea      1  

[374 rows x 14 columns]

In [5]:
df = df.drop(columns=['Person ID', 'Sleep Disorder'], axis=1)
df

Gender  Age            Occupation  Sleep Duration  Quality of Sleep  \
0      Male   27     Software Engineer             6.1                 6   
1      Male   28                Doctor             6.2                 6   
2      Male   28                Doctor             6.2                 6   
3      Male   28  Sales Representative             5.9                 4   
4      Male   28  Sales Representative             5.9                 4   
..      ...  ...                   ...             ...               ...   
369  Female   59                 Nurse             8.1                 9   
370  Female   59                 Nurse             8.0                 9   
371  Female   59                 Nurse             8.1                 9   
372  Female   59                 Nurse             8.1                 9   
373  Female   59                 Nurse             8.1                 9   

     Physical Activity Level  Stress Level BMI Category Blood Pressure  \
0                         42             6   Overweight         126/83   
1                         60             8       Normal         125/80   
2                         60             8       Normal         125/80   
3                         30             8        Obese         140/90   
4                         30             8        Obese         140/90   
..                       ...           ...          ...            ...   
369                       75             3   Overweight         140/95   
370                       75             3   Overweight         140/95   
371                       75             3   Overweight         140/95   
372                       75             3   Overweight         140/95   
373                       75             3   Overweight         140/95   

     Heart Rate  Daily Steps  Sleep  
0            77         4200      0  
1            75        10000      0  
2            75        10000      0  
3            85         3000      1  
4            85         3000      1  
..          ...          ...    ...  
369          68         7000      1  
370          68         7000      1  
371          68         7000      1  
372          68         7000      1  
373          68         7000      1  

[374 rows x 12 columns]

In [6]:
df[['Systolic', 'Diastolic']] = df['Blood Pressure'].str.split('/',expand=True)

# Convert to numeric values
df['Systolic'] = pd.to_numeric(df['Systolic'])
df['Diastolic'] = pd.to_numeric(df['Diastolic'])

df = df.drop(columns=['Blood Pressure'], axis=1)
df

Gender  Age            Occupation  Sleep Duration  Quality of Sleep  \
0      Male   27     Software Engineer             6.1                 6   
1      Male   28                Doctor             6.2                 6   
2      Male   28                Doctor             6.2                 6   
3      Male   28  Sales Representative             5.9                 4   
4      Male   28  Sales Representative             5.9                 4   
..      ...  ...                   ...             ...               ...   
369  Female   59                 Nurse             8.1                 9   
370  Female   59                 Nurse             8.0                 9   
371  Female   59                 Nurse             8.1                 9   
372  Female   59                 Nurse             8.1                 9   
373  Female   59                 Nurse             8.1                 9   

     Physical Activity Level  Stress Level BMI Category  Heart Rate  \
0                         42             6   Overweight          77   
1                         60             8       Normal          75   
2                         60             8       Normal          75   
3                         30             8        Obese          85   
4                         30             8        Obese          85   
..                       ...           ...          ...         ...   
369                       75             3   Overweight          68   
370                       75             3   Overweight          68   
371                       75             3   Overweight          68   
372                       75             3   Overweight          68   
373                       75             3   Overweight          68   

     Daily Steps  Sleep  Systolic  Diastolic  
0           4200      0       126         83  
1          10000      0       125         80  
2          10000      0       125         80  
3           3000      1       140         90  
4           3000      1       140         90  
..           ...    ...       ...        ...  
369         7000      1       140         95  
370         7000      1       140         95  
371         7000      1       140         95  
372         7000      1       140         95  
373         7000      1       140         95  

[374 rows x 13 columns]

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['Sleep']), df['Sleep'], test_size=0.3)

In [8]:
# apply Column Transformer
from sklearn.compose import ColumnTransformer

In [9]:
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder, FunctionTransformer

In [10]:
# ohe = ColumnTransformer(transformers=[
#     ('ohe', OneHotEncoder(sparse_output=False, drop='first', dtype=int), ['Occupation'])
# ], remainder='passthrough')

In [11]:
# ohe

In [12]:
# ohe = ohe.fit_transform(X_train)
# ohe

In [13]:
# ohe[0]

In [35]:
oe = ColumnTransformer(
    transformers=[
            ('tnf3', OrdinalEncoder(categories=[['Overweight', 'Normal', 'Obese', 'Normal Weight']], dtype=int), ['BMI Category'])
    ], remainder='passthrough'
)

oea = oe.fit_transform(df)

In [36]:
oea.shape

(374, 13)

In [31]:
oea[0]

array([0, 'Male', 27, 'Software Engineer', 6.1, 6, 42, 6, 77, 4200, 0,
       126, 83], dtype=object)

In [37]:
transformer = ColumnTransformer(transformers=[
    ('tnf1', OrdinalEncoder(categories=[['Male', 'Female']], dtype=int), ['Gender']),
    ('tnf2', OneHotEncoder(sparse_output=False, drop='first', dtype=int), ['Occupation']),
    ('tnf3', OrdinalEncoder(categories=[['Overweight', 'Normal', 'Obese', 'Normal Weight']], dtype=int), ['BMI Category'])
    # ('to_int', FunctionTransformer(to_int_transformer), ['Gender'])
], remainder='passthrough'
)


In [25]:
transfered_data = transformer.fit_transform(X_train)
transfered_data[0]

array([0.00e+00, 0.00e+00, 0.00e+00, 1.00e+00, 0.00e+00, 0.00e+00,
       0.00e+00, 0.00e+00, 0.00e+00, 0.00e+00, 0.00e+00, 4.10e+01,
       7.10e+00, 7.00e+00, 5.50e+01, 6.00e+00, 7.20e+01, 6.00e+03,
       1.25e+02, 8.20e+01])

In [20]:

print("transfered_data", transfered_data.shape)
print("X_train ",X_train.shape)


transfered_data (261, 20)
X_train  (261, 12)


In [21]:
transformer.fit_transform(X_test)

array([[1.00e+00, 0.00e+00, 0.00e+00, ..., 1.00e+04, 1.40e+02, 9.50e+01],
       [0.00e+00, 1.00e+00, 0.00e+00, ..., 8.00e+03, 1.20e+02, 8.00e+01],
       [1.00e+00, 0.00e+00, 0.00e+00, ..., 7.00e+03, 1.15e+02, 7.50e+01],
       ...,
       [1.00e+00, 0.00e+00, 0.00e+00, ..., 7.00e+03, 1.15e+02, 7.50e+01],
       [1.00e+00, 0.00e+00, 1.00e+00, ..., 5.00e+03, 1.25e+02, 8.00e+01],
       [1.00e+00, 0.00e+00, 0.00e+00, ..., 7.00e+03, 1.15e+02, 7.50e+01]])

In [22]:
from sklearn.linear_model import LogisticRegression
lg = LogisticRegression()

In [23]:
y_train

168    0
174    0
127    0
182    0
130    0
      ..
183    0
226    2
35     0
348    1
10     0
Name: Sleep, Length: 261, dtype: int64

In [38]:
# lg.fit(X_train, y_train)